version: "3.9"

services:

  postgres_fluvius:
    image: postgres:16-alpine
    container_name: fluvius_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluvius
    ports:
      - "5432:5432"
    volumes:
      - fluvius_postgres_data:/var/lib/postgresql/data

  postgres_evolution:
    image: postgres:16-alpine
    container_name: evolution_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution
      POSTGRES_DB: evolution
    ports:
      - "5433:5432"
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  redis_evolution:
    image: redis:7
    container_name: evolution_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  evolution_api:
    # image: atendai/evolution-api:v2.1.1
    image: evoapicloud/evolution-api:v2.3.7
    container_name: evolution_api
    restart: unless-stopped
    depends_on:
      - postgres_evolution
      - redis_evolution
    ports:
      - "8080:8080"
    env_file:
      - .env.evolution
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  fluvius_postgres_data:
  evolution_postgres_data:
  evolution_instances:
