"""add_media_fields_to_message

Revision ID: 375ddd2d2793
Revises: fc368c66c823
Create Date: 2026-05-07 08:45:43.921683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375ddd2d2793'
down_revision: Union[str, Sequence[str], None] = 'fc368c66c823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'mime_type')
    op.drop_column('messages', 'media_url')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
