"""add_agents_and_conversation_assignment

Revision ID: fc368c66c823
Revises: 31fb7a80de2b
Create Date: 2026-05-07 07:48:43.981009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc368c66c823'
down_revision: Union[str, Sequence[str], None] = '31fb7a80de2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=True)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.add_column('conversations', sa.Column('assignee_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversations_assignee_id'), 'conversations', ['assignee_id'], unique=False)
    # NOTE: SQLite does not support adding FK constraints to existing tables via ALTER TABLE.
    # The FK relationship is defined in the SQLAlchemy model and enforced at the application layer.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_assignee_id'), table_name='conversations')
    op.drop_column('conversations', 'resolved_at')
    op.drop_column('conversations', 'assigned_at')
    op.drop_column('conversations', 'assignee_id')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
